### ISSUE TITLE
Hello, when will the full code be published?

### ISSUE THREAD

**Issue by zmxsss** [OpenNLPLab/cosFormer#3]
diff += torch.norm(left_res - right_res)
What does diff stand for

**Comment by chinaliwenbo** [comment]
left_res is vanilla transfomer‘s result and right_res is cosFomer's result, the code use same W, compare attention output

**Comment by Doraemonzzz** [comment]
1. Diff is just to verify the correctness of the implementation.
2. Full code is in progress.
